# Generated by Django 6.0.3 on 2026-04-13 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_is_deleted_message_reply_to_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
